name: "JustTPA"
version: ${project.version}
main: "de.justplayer.tpa.Plugin"
api-version: '1.19'
author: "JustPlayer"
description: "A simple TPA plugin without unnecessary dependencies"
commands:
  tpa:
    description: "Teleport to a player"
    usage: "/tpa <player>"
    permission: "justplayer.tpa.request"
  tpaccept:
    description: "Accept a teleport request, optionally provide a player name to only accept from that player."
    usage: "/tpaccept [player]"
    permission: "justplayer.tpa.accept"
  tpadeny:
    description: "Deny a teleport request, optionally provide a player name to only deny from that player."
    usage: "/tpadeny [player]"
    permission: "justplayer.tpa.deny"
  tpacancel:
    description: "Cancel a teleport request"
    usage: "/tpacancel"
    permission: "justplayer.tpa.cancel"
  tpahere:
    description: "Request a player to teleport to you"
    usage: "/tpahere <player>"
    permission: "justplayer.tpa.here"
  tpareload:
    description: "Reload plugin configuration"
    usage: "/tpareload"
    permission: "justplayer.tpa.reload"
  tpareturn:
    description: "Returns you to the position before your teleport"
    usage: "/tpareturn"
    permission: "justplayer.tpa.return"
    aliases:
      - return
permissions:
  justplayer.tpa.request:
    description: "Allows a player to request a teleport"
    default: true
  justplayer.tpa.accept:
    description: "Allows a player to accept a teleport request"
    default: true
  justplayer.tpa.deny:
    description: "Allows a player to deny a teleport request"
    default: true
  justplayer.tpa.cancel:
    description: "Allows a player to cancel a teleport request"
    default: true
  justplayer.tpa.here:
    description: "Allows a player to request a player to teleport to them"
    default: true
  justplayer.tpa.return:
    description: "Allows a player to return to the previous position after teleportation"
    default: true
  justplayer.tpa.reload:
    description: "Allows a player to reload the plugin configuration"
    default: op
  justplayer.tpa.wait.bypass:
    description: "Allows a player to bypass the teleport wait time"
    default: op
