name: Feature Request
description: Use this template if you want to request features
title: 'Feature Request: '
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature should be.
      placeholder: Players should be able to teleport to other players...
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Additional context
      description: >-
        This field is here just in case you want to give additional information's or context.
  - type: checkboxes
    id: agree
    attributes:
      label: Verifying nothing is missing
      options:
        - label: I did search for a similar issue or feature request first
          required: true
  - type: markdown
    attributes:
      value: >-
        Please keep in mind that I may or may not add the requested feature, I will also try to keep features to a minimum that may not fit in the idea of a TPA plugin.
