name: dev-build

on:
  push:

concurrency: devbuild

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package "-Drevision=dev-${{ github.ref_name }}-${GITHUB_SHA::6}"
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          name: "Development build"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest-dev"
          prerelease: true
          files: |
            target/just-tpa-*.jar
