name: release

on:
  release:
    types: [published]

concurrency: release

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package "-Drevision=${{ github.event.release.tag_name }}"
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: GM9AuKjX
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          #modrinth-featured: true
          #modrinth-unfeature-mode: subset

          #curseforge-id: TODO? do i even want to publish on curseforge? idk
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            target/just-tpa-${{ github.event.release.tag_name }}.jar

          loaders: |
            spigot
            paper
            bukkit
          game-versions: |
            >1.19
          fail-mode: skip
